trigger adjustment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,14 +7,11 @@ jobs:
     name: merge request simulation
     runs-on: ubuntu-latest
     steps:
-      - name: backend deploy
-        run: |
-          echo "simulation of backend building.."
-          sleep 1s
+ 
       - name: run e2e tests from separate repo
         id: moto-api
         continue-on-error: true
-        uses: convictional/trigger-workflow-and-wait@v1.6.4
+        uses: convictional/trigger-workflow-and-wait@v1.6.4 
         with:
           owner: Karel-Danes
           repo: cypress-repo
@@ -24,20 +21,20 @@ jobs:
           ref: master
           client_payload: '{"tags":"true","environment":"alza","test-case":"alza"}'
         
-      - name: Job success
+      - name: E2E tests Success
         if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
         run: |
           echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
           echo "Detailed logs of Cypress run as a clue here ${{steps.moto-api.outputs.workflow_url}}"
           echo "ref is ${{github.ref}}"
-          echo "### All Cypress tests passed! :rocket: log here ${{steps.moto-api.outputs.workflow_url}} "  >> $GITHUB_STEP_SUMMARY
+          echo "### :white_check_mark: All E2E tests passed! :white_check_mark: log here ${{steps.moto-api.outputs.workflow_url}} "  >> $GITHUB_STEP_SUMMARY
 
-      - name: Job Failure debug
+      - name: E2E tests Failure debug
         if: (steps.moto-api.outputs.conclusion == 'failure')
         run: |
           echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
           echo "Detailed logs of Cypress run as a clue here ${{steps.moto-api.outputs.workflow_url}}"
           echo "ref is ${{github.ref}}"
-          echo "### Some Cypress tests failed! :skull: :bone: :skull: debug here ${{steps.moto-api.outputs.workflow_url}}"  >> $GITHUB_STEP_SUMMARY
-          exit 1
+          echo "### Some :X: E2E tests failed! :X: debug here ${{steps.moto-api.outputs.workflow_url}}"  >> $GITHUB_STEP_SUMMARY
+          exit 1 
 
